version: '2.1'
services:
  config-server:
    image: indiagator/skillwise-configserver:0.1
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"
  eureka-server:
    image: indiagator/skillwise-eureka:0.3
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      config-server:
        condition: service_started
    ports:
      - "8070:8070"
    networks:
      backend:
        aliases:
          - "eureka-server"
  userdetails-service:
    image: indiagator/skillwise-userdetails:0.3
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      config-server:
       condition: service_started
      eureka-server:
        condition: service_started
    ports:
      - "8091:8091"
    networks:
      - backend
  transactions-service:
    image: indiagator/skillwise-transactions:0.3
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    ports:
      - "8092:8092"
    networks:
      - backend
  #test-service-3:
   # image: indiagator/test-service-3-image-fresh:0.4
  #  environment:
   #   PROFILE: "default"
  #    CONFIGSERVER_URI: "http://config-server:8071"
  #    CONFIGSERVER_PORT: "8071"
   #   DATABASESERVER_PORT: "5432"
  #  depends_on:
   #   config-server:
  #      condition: service_started
   #   eureka-server:
   #     condition: service_started
   # ports:
    #  - "8082:8082"
   # networks:
   #   - backend
 # test-service-4:
  #  image: indiagator/test-service-4:0.3
   # environment:
   #   PROFILE: "default"
   #   CONFIGSERVER_URI: "http://config-server:8071"
   #   CONFIGSERVER_PORT: "8071"
   #   DATABASESERVER_PORT: "5432"
   # depends_on:
    #  config-server:
    #    condition: service_started
    #  eureka-server:
    #    condition: service_started
  #  ports:
 #    - "8086:8085"
  #  networks:
   #   - backend
 # gateway-server:
   # image: indiagator/gateway-server:0.1
   # environment:
   #   PROFILE: "default"
    #  CONFIGSERVER_URI: "http://config-server:8071"
    #  CONFIGSERVER_PORT: "8071"
    #  DATABASESERVER_PORT: "5432"
   # depends_on:
  #    config-server:
  #      condition: service_started
    #  eureka-server:
   #    condition: service_started
  #  ports:
  #   - "8072:8072"
   # networks:
   #  - backend

networks:
  backend:
    driver: bridge